#library(fitdistrplus)
library(rlang)
library(dplyr)
library(readr)     
library(stringr)
library(purrr)
library(tidyr)
library(lubridate)
#library(bizdays)
library(hms)
library(tis) # https://www.rdocumentation.org/packages/tis/versions/1.34/topics/holidays
library(RODBC)
library(tictoc)
library(ggplot2)
library(plotly)
library(tidytext)
library(tibble)
library(scales)
library(forcats)
library(broom)
library(modelr)
library(janitor)
library(lemon)
library(devtools)
#library(forecast)
library(astsa)
library(magrittr)
library(XML)
library(listviewer)
library(permute)
library(splitstackshape)
library(data.table)
# library(benchmarkme)
# library(cluster)
# library(lattice)
# library(profmem)
# library(profvis)
library(parallel)
library(doParallel)
library(foreach)
library(caret)
library(corrr)
library(vcd)
library(rebus)
#library(maps)
#library(ggmap)
library(ggthemes)
library(mapproj)
#library(tigris)
library(readxl)
library(FNN)
# library(microbenchmark)
library(solitude)
library(conflicted)

conflict_prefer("filter", "dplyr")
conflict_prefer("lag", "dplyr")
conflict_prefer("map", "purrr")
conflict_prefer("set_names", "magrittr")
